namespace LoLMatchHistory.API.Models;

public class GoldDto
{
    public required string GameHash { get; set; }
    public required string Type { get; set; }
    public required long Min1 { get; set; }
    public required long Min2 { get; set; }
    public required long Min3 { get; set; }
    public required long Min4 { get; set; }
    public required long Min5 { get; set; }
    public required long Min6 { get; set; }
    public required long Min7 { get; set; }
    public required long Min8 { get; set; }
    public required long Min9 { get; set; }
    public required long Min10 { get; set; }
    public required long Min11 { get; set; }
    public required long Min12 { get; set; }
    public required long Min13 { get; set; }
    public required long Min14 { get; set; }
    public required long Min15 { get; set; }
    public required long Min16 { get; set; }
    public required long Min17 { get; set; }
    public required long Min18 { get; set; }
    public required long Min19 { get; set; }
    public required long Min20 { get; set; }
    public required long Min21 { get; set; }
    public required long Min22 { get; set; }
    public required long Min23 { get; set; }
    public required long Min24 { get; set; }
    public required long Min25 { get; set; }
    public required long Min26 { get; set; }
    public required long Min27 { get; set; }
    public required long Min28 { get; set; }
    public required long Min29 { get; set; }
    public required long Min30 { get; set; }
    public required long Min31 { get; set; }
    public required long Min32 { get; set; }
    public required long Min33 { get; set; }
    public required long Min34 { get; set; }
    public required long Min35 { get; set; }
    public required long Min36 { get; set; }
    public required long Min37 { get; set; }
    public required long Min38 { get; set; }
    public required long Min39 { get; set; }
    public required long Min40 { get; set; }
    public required long Min41 { get; set; }
    public required long Min42 { get; set; }
    public required long Min43 { get; set; }
    public required long Min44 { get; set; }
    public required long Min45 { get; set; }
    public required long Min46 { get; set; }
    public required long Min47 { get; set; }
    public required long Min48 { get; set; }
    public required long Min49 { get; set; }
    public required long Min50 { get; set; }
    public required long Min51 { get; set; }
    public required long Min52 { get; set; }
    public required long Min53 { get; set; }
    public required long Min54 { get; set; }
    public required long Min55 { get; set; }
    public required long Min56 { get; set; }
    public required long Min57 { get; set; }
    public required long Min58 { get; set; }
    public required long Min59 { get; set; }
    public required long Min60 { get; set; }
    public required long Min61 { get; set; }
    public required long Min62 { get; set; }
    public required long Min63 { get; set; }
    public required long Min64 { get; set; }
    public required long Min65 { get; set; }
    public required long Min66 { get; set; }
    public required long Min67 { get; set; }
    public required long Min68 { get; set; }
    public required long Min69 { get; set; }
    public required long Min70 { get; set; }
    public required long Min71 { get; set; }
    public required long Min72 { get; set; }
    public required long Min73 { get; set; }
    public required long Min74 { get; set; }
    public required long Min75 { get; set; }
    public required long Min76 { get; set; }
    public required long Min77 { get; set; }
    public required long Min78 { get; set; }
    public required long Min79 { get; set; }
    public required long Min80 { get; set; }
    public required long Min81 { get; set; }
    public required long Min82 { get; set; }
    public required long Min83 { get; set; }
    public required long Min84 { get; set; }
    public required long Min85 { get; set; }
    public required long Min86 { get; set; }
    public required long Min87 { get; set; }
    public required long Min88 { get; set; }
    public required long Min89 { get; set; }
    public required long Min90 { get; set; }
    public required long Min91 { get; set; }
    public required long Min92 { get; set; }
    public required long Min93 { get; set; }
    public required long Min94 { get; set; }
    public required long Min95 { get; set; }
}
