using System.ComponentModel.DataAnnotations;

namespace LoLMatchHistory.Infrastructure.Models;
public class Gold
{
    [Key]
    public int Id { get; set; }
    public string GameHash { get; set; }
    public string Type { get; set; }
    public long? Min1 { get; set; }
    public long? Min2 { get; set; }
    public long? Min3 { get; set; }
    public long? Min4 { get; set; }
    public long? Min5 { get; set; }
    public long? Min6 { get; set; }
    public long? Min7 { get; set; }
    public long? Min8 { get; set; }
    public long? Min9 { get; set; }
    public long? Min10 { get; set; }
    public long? Min11 { get; set; }
    public long? Min12 { get; set; }
    public long? Min13 { get; set; }
    public long? Min14 { get; set; }
    public long? Min15 { get; set; }
    public long? Min16 { get; set; }
    public long? Min17 { get; set; }
    public long? Min18 { get; set; }
    public long? Min19 { get; set; }
    public long? Min20 { get; set; }
    public long? Min21 { get; set; }
    public long? Min22 { get; set; }
    public long? Min23 { get; set; }
    public long? Min24 { get; set; }
    public long? Min25 { get; set; }
    public long? Min26 { get; set; }
    public long? Min27 { get; set; }
    public long? Min28 { get; set; }
    public long? Min29 { get; set; }
    public long? Min30 { get; set; }
    public long? Min31 { get; set; }
    public long? Min32 { get; set; }
    public long? Min33 { get; set; }
    public long? Min34 { get; set; }
    public long? Min35 { get; set; }
    public long? Min36 { get; set; }
    public long? Min37 { get; set; }
    public long? Min38 { get; set; }
    public long? Min39 { get; set; }
    public long? Min40 { get; set; }
    public long? Min41 { get; set; }
    public long? Min42 { get; set; }
    public long? Min43 { get; set; }
    public long? Min44 { get; set; }
    public long? Min45 { get; set; }
    public long? Min46 { get; set; }
    public long? Min47 { get; set; }
    public long? Min48 { get; set; }
    public long? Min49 { get; set; }
    public long? Min50 { get; set; }
    public long? Min51 { get; set; }
    public long? Min52 { get; set; }
    public long? Min53 { get; set; }
    public long? Min54 { get; set; }
    public long? Min55 { get; set; }
    public long? Min56 { get; set; }
    public long? Min57 { get; set; }
    public long? Min58 { get; set; }
    public long? Min59 { get; set; }
    public long? Min60 { get; set; }
    public long? Min61 { get; set; }
    public long? Min62 { get; set; }
    public long? Min63 { get; set; }
    public long? Min64 { get; set; }
    public long? Min65 { get; set; }
    public long? Min66 { get; set; }
    public long? Min67 { get; set; }
    public long? Min68 { get; set; }
    public long? Min69 { get; set; }
    public long? Min70 { get; set; }
    public long? Min71 { get; set; }
    public long? Min72 { get; set; }
    public long? Min73 { get; set; }
    public long? Min74 { get; set; }
    public long? Min75 { get; set; }
    public long? Min76 { get; set; }
    public long? Min77 { get; set; }
    public long? Min78 { get; set; }
    public long? Min79 { get; set; }
    public long? Min80 { get; set; }
    public long? Min81 { get; set; }
    public long? Min82 { get; set; }
    public long? Min83 { get; set; }
    public long? Min84 { get; set; }
    public long? Min85 { get; set; }
    public long? Min86 { get; set; }
    public long? Min87 { get; set; }
    public long? Min88 { get; set; }
    public long? Min89 { get; set; }
    public long? Min90 { get; set; }
    public long? Min91 { get; set; }
    public long? Min92 { get; set; }
    public long? Min93 { get; set; }
    public long? Min94 { get; set; }
    public long? Min95 { get; set; }

}
