// <auto-generated />
using System;
using LoLMatchHistory.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoLMatchHistory.Infrastructure.Migrations
{
    [DbContext(typeof(LoLMatchHistoryContext))]
    [Migration("20250205123046_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LoLMatchHistory.Infrastructure.Models.Bans", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ban1")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Ban2")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Ban3")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Ban4")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Ban5")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GameHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("GameHash");

                    b.ToTable("Bans");
                });

            modelBuilder.Entity("LoLMatchHistory.Infrastructure.Models.Gold", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GameHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<long?>("Min1")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min10")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min11")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min12")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min13")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min14")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min15")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min16")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min17")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min18")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min19")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min2")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min20")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min21")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min22")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min23")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min24")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min25")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min26")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min27")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min28")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min29")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min3")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min30")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min31")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min32")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min33")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min34")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min35")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min36")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min37")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min38")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min39")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min4")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min40")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min41")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min42")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min43")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min44")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min45")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min46")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min47")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min48")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min49")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min5")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min50")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min51")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min52")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min53")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min54")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min55")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min56")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min57")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min58")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min59")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min6")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min60")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min61")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min62")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min63")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min64")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min65")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min66")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min67")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min68")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min69")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min7")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min70")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min71")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min72")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min73")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min74")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min75")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min76")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min77")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min78")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min79")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min8")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min80")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min81")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min82")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min83")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min84")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min85")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min86")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min87")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min88")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min89")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min9")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min90")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min91")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min92")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min93")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min94")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min95")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GameHash");

                    b.ToTable("Gold");
                });

            modelBuilder.Entity("LoLMatchHistory.Infrastructure.Models.Kill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Assist_1")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Assist_2")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Assist_3")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Assist_4")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GameHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Killer")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long?>("Time")
                        .HasColumnType("bigint");

                    b.Property<string>("Victim")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Xpos")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Ypos")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("GameHash");

                    b.ToTable("Kills");
                });

            modelBuilder.Entity("LoLMatchHistory.Infrastructure.Models.MatchInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BlueADC")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BlueADCChamp")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BlueJungle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BlueJungleChamp")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BlueMiddle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BlueMiddleChamp")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("BlueResult")
                        .HasColumnType("int");

                    b.Property<string>("BlueSupport")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BlueSupportChamp")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BlueTeamTag")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BlueTop")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BlueTopChamp")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GameHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("GameLength")
                        .HasColumnType("int");

                    b.Property<string>("League")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RedADC")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RedADCChamp")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RedJungle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RedJungleChamp")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RedMiddle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RedMiddleChamp")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RedResult")
                        .HasColumnType("int");

                    b.Property<string>("RedSupport")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RedSupportChamp")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RedTeamTag")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RedTop")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RedTopChamp")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("LoLMatchHistory.Infrastructure.Models.Monster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GameHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("Time")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("GameHash");

                    b.ToTable("Monsters");
                });

            modelBuilder.Entity("LoLMatchHistory.Infrastructure.Models.Structure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GameHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Lane")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long?>("Time")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("GameHash");

                    b.ToTable("Structures");
                });

            modelBuilder.Entity("LoLMatchHistory.Infrastructure.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LoLMatchHistory.Infrastructure.Models.Bans", b =>
                {
                    b.HasOne("LoLMatchHistory.Infrastructure.Models.MatchInfo", null)
                        .WithMany("Bans")
                        .HasForeignKey("GameHash")
                        .HasPrincipalKey("GameHash")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Bans_MatchInfo");
                });

            modelBuilder.Entity("LoLMatchHistory.Infrastructure.Models.Gold", b =>
                {
                    b.HasOne("LoLMatchHistory.Infrastructure.Models.MatchInfo", null)
                        .WithMany("Gold")
                        .HasForeignKey("GameHash")
                        .HasPrincipalKey("GameHash")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Gold_MatchInfo");
                });

            modelBuilder.Entity("LoLMatchHistory.Infrastructure.Models.Kill", b =>
                {
                    b.HasOne("LoLMatchHistory.Infrastructure.Models.MatchInfo", null)
                        .WithMany("Kills")
                        .HasForeignKey("GameHash")
                        .HasPrincipalKey("GameHash")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Kill_MatchInfo");
                });

            modelBuilder.Entity("LoLMatchHistory.Infrastructure.Models.Monster", b =>
                {
                    b.HasOne("LoLMatchHistory.Infrastructure.Models.MatchInfo", null)
                        .WithMany("Monsters")
                        .HasForeignKey("GameHash")
                        .HasPrincipalKey("GameHash")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Monster_MatchInfo");
                });

            modelBuilder.Entity("LoLMatchHistory.Infrastructure.Models.Structure", b =>
                {
                    b.HasOne("LoLMatchHistory.Infrastructure.Models.MatchInfo", null)
                        .WithMany("Structures")
                        .HasForeignKey("GameHash")
                        .HasPrincipalKey("GameHash")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Structure_MatchInfo");
                });

            modelBuilder.Entity("LoLMatchHistory.Infrastructure.Models.MatchInfo", b =>
                {
                    b.Navigation("Bans");

                    b.Navigation("Gold");

                    b.Navigation("Kills");

                    b.Navigation("Monsters");

                    b.Navigation("Structures");
                });
#pragma warning restore 612, 618
        }
    }
}
